-- AlterTable
ALTER TABLE "Calculations" ALTER COLUMN "sentEmail" SET DEFAULT NULL,
ALTER COLUMN "errorText" SET DEFAULT NULL;

-- AlterTable
ALTER TABLE "Images" ALTER COLUMN "src" SET DEFAULT NULL,
ALTER COLUMN "result" SET DEFAULT NULL,
ALTER COLUMN "sentEmail" SET DEFAULT NULL,
ALTER COLUMN "errorText" SET DEFAULT NULL;

-- AlterTable
ALTER TABLE "Videos" ALTER COLUMN "src" SET DEFAULT NULL,
ALTER COLUMN "result" SET DEFAULT NULL,
ALTER COLUMN "sentEmail" SET DEFAULT NULL,
ALTER COLUMN "errorText" SET DEFAULT NULL;
